/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121056-g36e374efb0-20250914"
#endif /* AVUTIL_FFVERSION_H */
