/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121059-g9e3c07f2df-20250914"
#endif /* AVUTIL_FFVERSION_H */
